{% set name = "go-jsonnet" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/go-jsonnet/archive/v{{ version }}.tar.gz
  sha256: ee7aa004e78fb49608bcf28142a7494dc204a07cc07d323dd2cff3d97298c696

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jsonnet --help

about:
  home: https://github.com/google/go-jsonnet
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Go implementation of configuration language for defining JSON data
  dev_url: https://github.com/google/go-jsonnet

extra:
  recipe-maintainers:
    - danielnachun
