schema_version: 1

context:
  version: "0.22.0"

package:
  name: go-jsonnet
  version: ${{ version }}

source:
  url: https://github.com/google/go-jsonnet/archive/v${{ version }}.tar.gz
  sha256: 9c463043a05c1e833c57136521e808ee8df192131f00c636235a2b54823d8c4c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - jsonnet --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Go implementation of configuration language for defining JSON data
  homepage: https://github.com/google/go-jsonnet
  repository: https://github.com/google/go-jsonnet

extra:
  recipe-maintainers:
    - danielnachun
